; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = black_f407ze
framework = arduino
monitor_speed = 115200
monitor_dtr = 1
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
    fastled/FastLED @ ^3.7.8
    SPI
lib_ldf_mode = deep+

[env:black_f407ze_dfu]
upload_protocol = dfu

[env:black_f407ze_stlink]
upload_protocol = stlink
