; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:blue_f407ve_mini]
platform = ststm32
board = blue_f407ve_mini
framework = arduino
upload_protocol = dfu
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
monitor_dtr = 1
monitor_speed = 115200
lib_deps = 
	iavorvel/MyLD2410@^1.2.8
	fastled/FastLED@^3.10.3
	adafruit/Adafruit NeoPixel@^1.15.5
    # 新增这一行：Adafruit 官方舵机驱动板库
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
	SPI  ; 👈 极其重要：强制引入内置 SPI 库，解决 BusIO 编译依赖


# 🛠️ 【最核心的修改】指示 PlatformIO 进行深度递归分析，彻底解决 SPI.h 找不到的顽疾
lib_ldf_mode = deep+